"""Resolve requirements to a pinned list for the Lambda's platform, not the build host's.

pip's --platform selects wheel tags but never re-evaluates environment markers:
those always describe the machine running pip. mcp depends on pywin32 under
`sys_platform == "win32"`, so a resolve on Windows insists on a package with no
manylinux wheel and the build fails outright. Resolving here and installing the
result with --no-deps keeps pip's real resolution while dropping the packages
that exist only for the build machine's operating system.
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path

# Packages that only ever exist to serve the build host's OS.
HOST_ONLY = {"pywin32", "pywin32-ctypes", "colorama"}


def resolve(requirements: Path) -> list[str]:
    with tempfile.TemporaryDirectory() as tmp:
        report = Path(tmp) / "report.json"
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "--quiet", "--dry-run", "--ignore-installed",
             "--report", str(report), "-r", str(requirements)],
            check=True,
        )
        data = json.loads(report.read_text(encoding="utf-8"))
    pins = []
    for item in data.get("install", []):
        info = item.get("metadata", {})
        name = (info.get("name") or "").lower()
        if name in HOST_ONLY:
            continue
        pins.append(f"{info['name']}=={info['version']}")
    return sorted(pins, key=str.lower)


def main() -> int:
    src, dest = Path(sys.argv[1]), Path(sys.argv[2])
    pins = resolve(src)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("# Generated by scripts/resolve_deps.py - do not edit.\n" + "\n".join(pins) + "\n",
                    encoding="utf-8")
    print(f"resolved {len(pins)} packages -> {dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
